# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53aca30eda8a125f3dd341e737d99fa734de9d9fcd230fd47644391acb0069ca72443bbe57d7db531880b3bb838064b1856335ab3ec0e55e3d7da7843c2c4424

test:
  secret_key_base: b785341afc584849785e90a2b66a3e8ff9df58264991dd964f4b96d90dd4c235e204b05d6801bcd3c0c330f900ca2908e99d89ae10413d0f6c453d29aed64f87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
